name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: moneymeets/action-setup-python-poetry@master
        with:
          python_version: 3.7

      - run: poetry run flake8

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        django-version: ["~2.2", "~3.0", "~3.1", "~3.2", "~4.0", "~4.1"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: moneymeets/action-setup-python-poetry@master
        with:
          python_version: ${{ matrix.python-version }}

      - name: Set up Django ${{ matrix.django-version }}
        run: poetry add Django${{ matrix.django-version }}

      - run: poetry run python runtests.py
